version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: kiosk-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-strapi123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kiosk-network

  # Strapi Backend
  strapi:
    build: ./kiosk-backend
    container_name: kiosk-backend
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-strapi123}
      DATABASE_SSL: false
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-here}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET:-your-admin-jwt-secret-here}
      APP_KEYS: ${APP_KEYS:-key1,key2,key3,key4}
      API_TOKEN_SALT: ${API_TOKEN_SALT:-your-api-token-salt}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT:-your-transfer-token-salt}
      NODE_ENV: ${NODE_ENV:-development}
      # Cloudinary (optional - remove if using local storage)
      CLOUDINARY_NAME: ${CLOUDINARY_NAME:-}
      CLOUDINARY_KEY: ${CLOUDINARY_KEY:-}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET:-}
    volumes:
      - ./kiosk-backend:/app
      - strapi_uploads:/app/public/uploads
      - strapi_node_modules:/app/node_modules
    ports:
      - "1337:1337"
    networks:
      - kiosk-network
    depends_on:
      - postgres

  # Frontend Web Application
  frontend:
    image: nginx:alpine
    container_name: kiosk-frontend
    restart: unless-stopped
    volumes:
      - ./frontend-kiosk:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - kiosk-network
    depends_on:
      - strapi

  # MQTT Broker for IoT devices (optional)
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: kiosk-mqtt
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - kiosk-network

networks:
  kiosk-network:
    driver: bridge

volumes:
  postgres_data:
  strapi_uploads:
  strapi_node_modules:
  mosquitto_data:
  mosquitto_log: