[build]
  # Set the base directory to museum-kiosk
  base = "museum-kiosk"
  
  # Build command
  command = "npm run build"
  
  # Output directory after build (relative to base)
  publish = "dist"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/viewer/*"
  [headers.values]
    # No cache for dynamic viewer pages
    Cache-Control = "no-cache, no-store, must-revalidate"

# API routes redirect to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables
[context.production.environment]
  ASTRO_TELEMETRY_DISABLED = "1"

[context.deploy-preview.environment]
  ASTRO_TELEMETRY_DISABLED = "1"

[context.branch-deploy.environment]
  ASTRO_TELEMETRY_DISABLED = "1"