[build]
  # Basis-Verzeichnis für den Build
  base = "museum-kiosk/"
  
  # Build-Befehl
  command = "npm run build"
  
  # Output-Verzeichnis nach dem Build
  publish = "dist"

[build.environment]
  # Node Version
  NODE_VERSION = "18"

# Redirects und Headers für SPA
[[headers]]
  for = "/*"
  [headers.values]
    # Cache-Control für statische Assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/viewer/*"
  [headers.values]
    # Kein Cache für dynamische Viewer-Pages
    Cache-Control = "no-cache, no-store, must-revalidate"

# API-Routes werden zu Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Umgebungsvariablen (in Netlify UI setzen)
[context.production.environment]
  # Für Production
  ASTRO_TELEMETRY_DISABLED = "1"

[context.deploy-preview.environment]
  # Für Preview Deployments
  ASTRO_TELEMETRY_DISABLED = "1"

[context.branch-deploy.environment]
  # Für Branch Deployments
  ASTRO_TELEMETRY_DISABLED = "1"