[build]
  # Build-Befehl
  command = "npm run build"
  
  # Output-Verzeichnis nach dem Build
  publish = "dist"

[build.environment]
  # Node Version
  NODE_VERSION = "18"

# Headers für statische Assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/viewer/*"
  [headers.values]
    # Kein Cache für dynamische Viewer-Pages
    Cache-Control = "no-cache, no-store, must-revalidate"

# API-Routes werden zu Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Keine SPA Fallback für Astro SSR

# Umgebungsvariablen (in Netlify UI setzen)
[context.production.environment]
  # Für Production
  ASTRO_TELEMETRY_DISABLED = "1"

[context.deploy-preview.environment]
  # Für Preview Deployments
  ASTRO_TELEMETRY_DISABLED = "1"

[context.branch-deploy.environment]
  # Für Branch Deployments
  ASTRO_TELEMETRY_DISABLED = "1"