services:
  - type: web
    name: museum-kiosk-backend
    runtime: node
    repo: https://github.com/museumgrueneshaus/kiosk-backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: true
      - key: DATABASE_SSL_REJECT_UNAUTHORIZED
        value: false
      - key: CLOUDINARY_NAME
        value: dtx5nuban
      - key: CLOUDINARY_KEY
        value: 484387353599576
      - key: CLOUDINARY_SECRET
        sync: false # Markiert als Secret
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: museum-kiosk-db
          property: connectionString

databases:
  - name: museum-kiosk-db
    plan: starter
    databaseName: museum_kiosk
    user: museum_admin